AWSTemplateFormatVersion: "2010-09-09"
Description: A Template to provision Amazon Location Service resources for js-map-with-geojson-point

# Create an API key that has access to maps
Resources:
  AmazonLocationApiKey:
    Type: AWS::Location::APIKey
    DeletionPolicy: Retain
    Properties:
      KeyName: js-map-with-geojson-point
      Description: API Key for Amazon Location Service Maps
      NoExpiry: true
      Restrictions:
        AllowActions:
          - "geo-maps:*"
        AllowResources:
          - !Sub "arn:aws:geo-maps:${AWS::Region}::provider/default"

Outputs:
  ApiKey:
    Value: !Ref AmazonLocationApiKey

  Region:
    Value: !Sub ${AWS::Region}
